production:
  storage: :s3
  s3_credentials:
    bucket: <%= ENV['AMAZON_BUCKET'] %>
    host_name: <%= ENV['AMAZON_HOST_NAME'] %>
    access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AMAZON_SECRET_KEY'] %>

development:
  storage: :s3
  s3_credentials:
    bucket: <%= ENV['AMAZON_BUCKET'] %>
    host_name: <%= ENV['AMAZON_HOST_NAME'] %>
    access_key_id: <%= ENV['AMAZON_ACCESS_KEY_ID'] %>
    secret_access_key: <%= ENV['AMAZON_SECRET_KEY'] %>
