# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a5e9f1abc666fc350d7d62020f705845ebe93c41d345d65455359c4437d4696daed213347c4c02a02b1cb8e8900b24589615630a73f328453cee9394b8ff2e5

test:
  secret_key_base: 984a205cd7ad89d7cb30891fd950a6dbcc87b53065fafd5b17f58a1ff42a5e4efabee7eaa3e0be2936e279ddaaf43579ff712037f812ea4f0d20c6dd4d023df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
